-- MySQL Script generated by MySQL Workbench
-- Wed Jun 23 18:25:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema Gestor-E
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Gestor-E` DEFAULT CHARACTER SET utf8 ;

-- -----------------------------------------------------
-- Table Gestor-E.Roles
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Roles (
  RolId INT NOT NULL AUTO_INCREMENT,
  RolName VARCHAR(45) NOT NULL,
  RolDescription VARCHAR(80) NULL,
  PRIMARY KEY (RolId))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table Gestor-E.Users
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Users (
  UserId INT NOT NULL AUTO_INCREMENT,
  Identification INT NOT NULL,
  Name1 VARCHAR(45) NOT NULL,
  Name2 VARCHAR(45) NULL,
  Name3 VARCHAR(45) NOT NULL,
  Name4 VARCHAR(45) NULL,
  UserName VARCHAR(45) NOT NULL,
  Password VARCHAR(45) NOT NULL,
  UserEmail VARCHAR(65) NOT NULL,
  Roles_RolId INT NOT NULL,
  PRIMARY KEY (UserId, Roles_RolId),
  INDEX fk_Users_Roles1_idx (Roles_RolId ASC),
  CONSTRAINT fk_Users_Roles1
    FOREIGN KEY (Roles_RolId)
    REFERENCES Roles (RolId)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table Gestor-E.Suppliers
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Suppliers (
  SupplierId INT NOT NULL AUTO_INCREMENT,
  SupplierName VARCHAR(70) NOT NULL,
  SupplierPhone INT NOT NULL,
  SupplierAddress VARCHAR(45) NOT NULL,
  SupplierDescription VARCHAR(150) NULL,
  SupplierWeb VARCHAR(65) NULL,
  SupplierEmail VARCHAR(45) NULL,
  CreateDate DATE NOT NULL,
  Users_UserId INT NOT NULL,
  PRIMARY KEY (SupplierId),
  INDEX fk_Suppliers_Users1_idx (Users_UserId ASC),
  CONSTRAINT fk_Suppliers_Users1
    FOREIGN KEY (Users_UserId)
    REFERENCES Users (UserId)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table Gestor-E.Categories
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Categories (
  CategoryId INT NOT NULL AUTO_INCREMENT,
  CategoryName VARCHAR(45) NOT NULL,
  CategoryDescription VARCHAR(45) NULL,
  CreateDate DATE NOT NULL,
  Users_UserId INT NOT NULL,
  Users_Roles_RolId INT NOT NULL,
  PRIMARY KEY (CategoryId),
  INDEX fk_Categories_Users1_idx (Users_UserId ASC, Users_Roles_RolId ASC),
  CONSTRAINT fk_Categories_Users1
    FOREIGN KEY (Users_UserId , Users_Roles_RolId)
    REFERENCES Users (UserId , Roles_RolId)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table Gestor-E.Bills
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Bills (
  Billid INT NOT NULL,
  BillName VARCHAR(45) NULL,
  BillDescription VARCHAR(45) NULL,
  BillDate DATE NULL,
  PRIMARY KEY (Billid))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table Gestor-E.Products
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Products (
  ProductId INT NOT NULL AUTO_INCREMENT,
  ProductName VARCHAR(45) NOT NULL,
  ProductPrice VARCHAR(45) NOT NULL,
  ProductAmount VARCHAR(45) NOT NULL,
  ProductDescription VARCHAR(250) NULL,
  CreateDate DATE NOT NULL,
  Categories_CategoryId INT NOT NULL,
  Users_UserId INT NOT NULL,
  Suppliers_SupplierId INT NOT NULL,
  Bills_Billid INT NOT NULL,
  PRIMARY KEY (ProductId, Categories_CategoryId),
  INDEX fk_Products_Categories1_idx (Categories_CategoryId ASC),
  INDEX fk_Products_Users1_idx (Users_UserId ASC),
  INDEX fk_Products_Suppliers1_idx (Suppliers_SupplierId ASC),
  INDEX fk_Products_Bills1_idx (Bills_Billid ASC),
  CONSTRAINT fk_Products_Categories1
    FOREIGN KEY (Categories_CategoryId)
    REFERENCES Categories (CategoryId)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Products_Users1
    FOREIGN KEY (Users_UserId)
    REFERENCES Users (UserId)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Products_Suppliers1
    FOREIGN KEY (Suppliers_SupplierId)
    REFERENCES Suppliers (SupplierId)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Products_Bills1
    FOREIGN KEY (Bills_Billid)
    REFERENCES Bills (Billid)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table Gestor-E.Requests
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Requests (
  RequestId INT NOT NULL AUTO_INCREMENT,
  Users_UserId INT NOT NULL,
  RequestDescription VARCHAR(200) NULL,
  Products_ProductId INT NOT NULL,
  Products_Categories_CategoryId INT NOT NULL,
  RequestDateStart DATE NOT NULL,
  RequestStatus VARCHAR(45) NOT NULL,
  RequestsAmount VARCHAR(45) NOT NULL,
  RequestDateEnd DATE NULL,
  PRIMARY KEY (RequestId),
  INDEX fk_Requests_Users1_idx (Users_UserId ASC),
  INDEX fk_Requests_Products1_idx (Products_Categories_CategoryId ASC, Products_ProductId ASC),
  CONSTRAINT fk_Requests_Users1
    FOREIGN KEY (Users_UserId)
    REFERENCES Users (UserId)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Requests_Products1
    FOREIGN KEY (Products_Categories_CategoryId , Products_ProductId)
    REFERENCES Products (Categories_CategoryId , ProductId)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
